name = "MultiFloats"
uuid = "bdf0d083-296b-4888-a5b6-7498122e68a5"
authors = ["David K. Zhang <dzhang314@gmail.com>"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.0"
