name = "MultiFloats"
uuid = "bdf0d083-296b-4888-a5b6-7498122e68a5"
version = "3.0.0"
authors = ["David K. Zhang <dzhang314@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPFR_jll = "3a97d323-0669-5f0c-9066-3539efd106a3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[compat]
SIMD = "^3"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
